spring:
  application:
    name: JavaAPI
  mongodb:
    host: localhost
    port: 27017
    database: geminiDB
  kafka:
    bootstrap-servers: <YOUR_SERVER>:<YOUR_PORT>
    consumer:
      group-id: javaapi-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type-mappings: |
              ArraysInput: com.rahul.JavaAPI.models.ArraysInput
  ai:
    mcp:
      server:
        type: SYNC
        name: JavaMcpServer
        version: 1.0.0
        protocol: streamable
        capabilities:
          tool: true
gemini:
  apiKey: <YOUR_GEMINI_API_KEY>
  model: gemini-1.5-pro
  # Optional: Set the logging level for MCP interactions to TRACE for detailed debugging
# logging:
#   level:
#     org:
#       springframework:
#         ai:
#           mcp: TRACE
#           server: TRACE
#     io:
#       modelcontextprotocol: TRACE
